version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          name: Install Dependencies
          command: npm install

      - cypress/run:
          name: Testing Project
          requires:
            - Install Dependencies
          debug: 'cypress:cli'
          attach-workspace: true
          command: npm run ci-test

      - cypress/run:
          name: Building Project
          requires:
            - Testing Project
          attach-workspace: true
          command: npm run build
          post-steps:
            - persist_to_workspace:
                root: ~/
                paths: 
                  - project