version: 2.1
orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@3.1.3

# define jobs
jobs:
  run-test:
    executor: cypress/default
    steps:
      - cypress/install
      - cypress/run-tests:
          cypress-command: npx wait-on@latest http://localhost:8080 && npx cypress run
          start-command: npm start
  build-project:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: build project
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

# define workflows
workflows:
  test-build:
    jobs:
      - run-test
      - build-project:
          requires:
            - run-test