version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      - cypress/run:
          name: Install Dependencies
          command: npm install

      # - cypress/run:
      #     name: Testing Project
      #     requires:
      #       - Install Dependencies
      #     debug: "cypress:cli"
      #     attach-workspace: true
      #     command: npm run ci-test

      - cypress/run:
          name: Building Project
          requires:
            - Install Dependencies
          attach-workspace: true
          command: npm run build
          post-steps:
            - persist_to_workspace:
                root: ~/
                paths:
                  - project

      - cypress/run:
          name: Alpha Netlify Release
          requires:
            - Building Project
          attach-workspace: true
          start: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          command: npx semantic-release
          post-steps:
            # trigger netlify build and deploy
            - run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/64db48100f6d0b4471e4eba4
          filters:
            branches:
              only: alpha
