// Wine action types
export enum WineActionType {
    UPDATE_NUM_UNIQUE_WINE = 'UPDATE_NUM_UNIQUE_WINE',
    UPDATE_NUM_UNIQUE_COUNTRY = 'UPDATE_NUM_UNIQUE_COUNTRY',
    START_FINDING_WINE = 'START_FINDING_WINE',
    UPDATE_WINE_LIST = 'UPDATE_WINE_LIST',
    END_FINDING_WINE = 'END_FINDING_WINE',
}
